/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const MediatoolThemeProviderPage = () => (
  <ReferencePage data={{"tags":{"see":"{@link https://northlight.dev/reference/mediatool-theme-provider}","example":"Should pass down a theme from northlight/ui, currently exports two themes:\n* theme - light mode\n* tottTheme - dark mode"},"filePath":"lib/components/mediatool-theme-provider/mediatool-theme-provider.tsx","description":"Should be at the root of you project, wraps the app in the theme context","displayName":"MediatoolThemeProvider","methods":[],"props":{"children":{"defaultValue":null,"description":"","name":"children","parent":{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"},"declarations":[{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"}],"required":true,"type":{"name":"enum","raw":"ReactNode","value":[{"value":"string"},{"value":"number"},{"value":"false"},{"value":"true"},{"value":"ReactElement<any, string | JSXElementConstructor<any>>","description":"","fullComment":"","tags":{}},{"value":"ReactFragment","description":"","fullComment":"","tags":{}},{"value":"ReactPortal","description":"","fullComment":"","tags":{}}]}},"theme":{"defaultValue":{"value":"extendTheme(overrides, WebappSkin)"},"description":"","name":"theme","parent":{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"},"declarations":[{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"}],"required":false,"type":{"name":"Record<string, any>"}},"themeName":{"defaultValue":{"value":"webappTheme"},"description":"","name":"themeName","parent":{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"},"declarations":[{"fileName":"framework/lib/components/mediatool-theme-provider/types.ts","name":"MediatoolThemeProviderProps"}],"required":false,"type":{"name":"enum","raw":"CurrentTheme","value":[{"value":"\"webappTheme\""},{"value":"\"tottTheme\""}]}}}}} />
);

export default MediatoolThemeProviderPage
