/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const StepPage = () => (
  <ReferencePage data={{"tags":{"see":"StepList *\nSteps *\n{@link https://northlight.dev/reference/step}","example":"(? <Step label=\"Step 1\" description=\"Personal information\" /> ?)"},"filePath":"lib/components/steps/step.tsx","description":"Renders a step in a step list","displayName":"Step","methods":[],"props":{"label":{"defaultValue":null,"description":"","name":"label","parent":{"fileName":"framework/lib/components/steps/types.ts","name":"StepProps"},"declarations":[{"fileName":"framework/lib/components/steps/types.ts","name":"StepProps"}],"required":true,"type":{"name":"string"}},"description":{"defaultValue":null,"description":"","name":"description","parent":{"fileName":"framework/lib/components/steps/types.ts","name":"StepProps"},"declarations":[{"fileName":"framework/lib/components/steps/types.ts","name":"StepProps"}],"required":false,"type":{"name":"string"}},"id":{"defaultValue":null,"description":"","name":"id","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"}],"required":false,"type":{"name":"string"}},"isSelected":{"defaultValue":{"value":"false"},"description":"","name":"isSelected","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"}],"required":false,"type":{"name":"enum","raw":"boolean","value":[{"value":"false"},{"value":"true"}]}},"panelId":{"defaultValue":null,"description":"","name":"panelId","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"}],"required":false,"type":{"name":"string"}},"isDisabled":{"defaultValue":{"value":"false"},"description":"If `true`, the `Tab` won't be toggleable","name":"isDisabled","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabOptions"}],"required":false,"type":{"name":"enum","raw":"boolean","value":[{"value":"false"},{"value":"true"}]}}}}} />
);

export default StepPage
