/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const AccordionItemPage = () => (
  <ReferencePage data={{"tags":{},"filePath":"lib/components/accordion/accordion-item.tsx","description":"","displayName":"AccordionItem","methods":[],"props":{"children":{"defaultValue":null,"description":"","name":"children","parent":{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/accordion-item.d.ts","name":"AccordionItemProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/accordion-item.d.ts","name":"AccordionItemProps"}],"required":false,"type":{"name":"enum","raw":"ReactNode | ((props: { isExpanded: boolean; isDisabled: boolean; }) => ReactNode)","value":[{"value":"string"},{"value":"number"},{"value":"false"},{"value":"true"},{"value":"ReactElement<any, string | JSXElementConstructor<any>>","description":"","fullComment":"","tags":{}},{"value":"ReactFragment","description":"","fullComment":"","tags":{}},{"value":"ReactPortal","description":"","fullComment":"","tags":{}},{"value":"(props: { isExpanded: boolean; isDisabled: boolean; }) => ReactNode","description":"","fullComment":"","tags":{}}]}},"isDisabled":{"defaultValue":{"value":"false"},"description":"If `true`, the accordion item will be disabled.","name":"isDisabled","parent":{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"}],"required":false,"type":{"name":"enum","raw":"boolean","value":[{"value":"false"},{"value":"true"}]}},"isFocusable":{"defaultValue":{"value":"false"},"description":"If `true`, the accordion item will be focusable.","name":"isFocusable","parent":{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"}],"required":false,"type":{"name":"enum","raw":"boolean","value":[{"value":"false"},{"value":"true"}]}},"id":{"defaultValue":null,"description":"A unique id for the accordion item.","name":"id","parent":{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/accordion/dist/use-accordion.d.ts","name":"UseAccordionItemProps"}],"required":false,"type":{"name":"string"}}}}} />
);

export default AccordionItemPage
