import { IconType } from '../../types'
import {
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CheckedIconFilled,
  FolderOpenIcon,
  HourGlassIcon,
  HubIcon,
  InfoFilled,
  MediatoolLogoIcon,
  MessageIconFilled,
  MinusIconFilled,
  PlugIcon,
  PlusIcon,
  PositionMarkerIcon,
  RefreshIcon,
  ReportIcon,
  SearchIcon,
  SettingsIcon,
  StatusPendingFilled,
  SwitchesIcon,
  ThreeDotsIconFilled,
  WarningFilled,
} from '../icons'

export const iconMap: Record<IconType, React.ComponentType<any>> = {
  hub: HubIcon,
  plug: PlugIcon,
  plus: PlusIcon,
  search: SearchIcon,
  switches: SwitchesIcon,
  mediatoolLogo: MediatoolLogoIcon,
  settings: SettingsIcon,
  folderOpen: FolderOpenIcon,
  positionMarker: PositionMarkerIcon,
  report: ReportIcon,
  approved: CheckedIconFilled,
  rejected: MinusIconFilled,
  working: RefreshIcon,
  pending: HourGlassIcon,
  messageFilled: MessageIconFilled,
  caretDown: CaretDownIcon,
  caretRight: CaretRightIcon,
  caretUp: CaretUpIcon,
  caretLeft: CaretLeftIcon,
  threeDots: ThreeDotsIconFilled,
  alertFilled: StatusPendingFilled,
  infoFilled: InfoFilled,
  warningFilled: WarningFilled,
}
