/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const LabelPage = () => (
  <ReferencePage data={{"tags":{"see":"Blockquote *\nLead *\nSmall *\nTiny *\n{@link https://northlight.dev/reference/label }","example":"(?\n<Label sx={{color: 'brand.500' }} size=\"lg\">Brand</Label>\n?)\n(_Note, all other css properties not listed\nunder the props tab to right should be passed down via **sx**_)"},"filePath":"/Users/sebastian.delgado/Documents/Programmering/Mediatool/northlight/framework/lib/components/typography/labels/label.tsx","description":"One of the stylized typography components","displayName":"Label","methods":[],"props":{"size":{"defaultValue":{"value":"sm"},"description":"","name":"size","parent":{"fileName":"framework/lib/components/typography/labels/types.ts","name":"LabelProps"},"declarations":[{"fileName":"framework/lib/components/typography/labels/types.ts","name":"LabelProps"}],"required":false,"type":{"name":"enum","raw":"LabelSizes","value":[{"value":"\"sm\""},{"value":"\"md\""},{"value":"\"lg\""},{"value":"\"2xs\""},{"value":"\"xs\""}]}},"requiredIndicator":{"defaultValue":null,"description":"","name":"requiredIndicator","parent":{"fileName":"northlight/node_modules/@chakra-ui/form-control/dist/form-label.d.ts","name":"FormLabelProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/form-control/dist/form-label.d.ts","name":"FormLabelProps"}],"required":false,"type":{"name":"ReactElement<any, string | JSXElementConstructor<any>>"}},"optionalIndicator":{"defaultValue":null,"description":"","name":"optionalIndicator","parent":{"fileName":"northlight/node_modules/@chakra-ui/form-control/dist/form-label.d.ts","name":"FormLabelProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/form-control/dist/form-label.d.ts","name":"FormLabelProps"}],"required":false,"type":{"name":"enum","raw":"ReactNode","value":[{"value":"string"},{"value":"number"},{"value":"false"},{"value":"true"},{"value":"ReactElement<any, string | JSXElementConstructor<any>>","description":"","fullComment":"","tags":{}},{"value":"ReactFragment","description":"","fullComment":"","tags":{}},{"value":"ReactPortal","description":"","fullComment":"","tags":{}}]}}}}} />
);

export default LabelPage
