/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const OverflowGroupPage = () => (
  <ReferencePage data={{"tags":{},"filePath":"/Users/sebastian.delgado/Documents/Programmering/Mediatool/northlight/framework/lib/components/overflow-group/overflow-group.tsx","description":"","displayName":"OverflowGroup","methods":[],"props":{"childrenProps":{"defaultValue":null,"description":"","name":"childrenProps","parent":{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"},"declarations":[{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"}],"required":false,"type":{"name":"Record<string, any>"}},"max":{"defaultValue":null,"description":"","name":"max","parent":{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"},"declarations":[{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"}],"required":false,"type":{"name":"number"}},"children":{"defaultValue":null,"description":"","name":"children","parent":{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"},"declarations":[{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"}],"required":true,"type":{"name":"enum","raw":"Element[] | React.ReactNode[]","value":[{"value":"Element[]","description":"","fullComment":"","tags":{}},{"value":"React.ReactNode[]","description":"","fullComment":"","tags":{}}]}},"onChange":{"defaultValue":null,"description":"","name":"onChange","parent":{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"},"declarations":[{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"}],"required":false,"type":{"name":"(nbrRemainingChildren: number) => void"}},"rect":{"defaultValue":null,"description":"","name":"rect","parent":{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"},"declarations":[{"fileName":"framework/lib/components/overflow-group/types.ts","name":"OverflowGroupProps"}],"required":false,"type":{"name":"HTMLElement"}}}}} />
);

export default OverflowGroupPage
