/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const SortablePage = () => (
  <ReferencePage data={{"tags":{"see":"DragAndDrop *\nSortableList *\nMultiSort *\n{@link https://northlight.dev}\n{@link https://docs.dndkit.com/presets/sortable/sortable-context}","example":"**<a href=\"https://docs.dndkit.com/presets/sortable/sortable-context\" target=\"_blank\">Read more on dnd-docs</a>**"},"filePath":"/Users/sebastian.delgado/Documents/Programmering/Mediatool/northlight/framework/lib/components/drag-and-drop/sortable.tsx","description":"Wrapper that provides context for sortable elements using DnD-kit","displayName":"Sortable","methods":[],"props":{"children":{"defaultValue":null,"description":"","name":"children","parent":{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"},"declarations":[{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"}],"required":true,"type":{"name":"React.ReactNode"}},"items":{"defaultValue":null,"description":"","name":"items","parent":{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"},"declarations":[{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"}],"required":true,"type":{"name":"(UniqueIdentifier | { id: UniqueIdentifier; })[]"}},"strategy":{"defaultValue":null,"description":"","name":"strategy","parent":{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"},"declarations":[{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"}],"required":false,"type":{"name":"SortingStrategy"}},"id":{"defaultValue":null,"description":"","name":"id","parent":{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"},"declarations":[{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"}],"required":false,"type":{"name":"string"}},"disabled":{"defaultValue":null,"description":"","name":"disabled","parent":{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"},"declarations":[{"fileName":"northlight/node_modules/@dnd-kit/sortable/dist/components/SortableContext.d.ts","name":"Props"}],"required":false,"type":{"name":"enum","raw":"boolean | Disabled","value":[{"value":"false"},{"value":"true"},{"value":"Disabled","description":"","fullComment":"","tags":{}}]}}}}} />
);

export default SortablePage
