/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const StepListPage = () => (
  <ReferencePage data={{"tags":{"see":"Step *\nSteps *\n{@link https://northlight.dev/reference/step-list}","example":"(?\n     <StepList>\n       <Step label=\"Step 1\" description=\"Name and email\" />\n       <Step label=\"Step 2\" description=\"Pick a password\" />\n       <Step label=\"Step 3\" description=\"Review\" />\n     </StepList>\n?)"},"filePath":"/Users/orestisrodriguez/Documents/Projects/@mediatool/northlight/framework/lib/components/steps/step-list.tsx","description":"Used to render a navigational list of steps","displayName":"StepList","methods":[],"props":{"children":{"defaultValue":null,"description":"","name":"children","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"}],"required":false,"type":{"name":"enum","raw":"ReactNode","value":[{"value":"string"},{"value":"number"},{"value":"false"},{"value":"true"},{"value":"ReactElement<any, string | JSXElementConstructor<any>>","description":"","fullComment":"","tags":{}},{"value":"ReactFragment","description":"","fullComment":"","tags":{}},{"value":"ReactPortal","description":"","fullComment":"","tags":{}}]}},"onKeyDown":{"defaultValue":null,"description":"","name":"onKeyDown","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"}],"required":false,"type":{"name":"KeyboardEventHandler<Element>"}},"ref":{"defaultValue":null,"description":"","name":"ref","parent":{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/tabs/dist/use-tabs.d.ts","name":"UseTabListProps"}],"required":false,"type":{"name":"enum","raw":"Ref<any>","value":[{"value":"(instance: any) => void","description":"","fullComment":"","tags":{}},{"value":"RefObject<any>","description":"","fullComment":"","tags":{}}]}}}}} />
);

export default StepListPage
