name: Lerna publish

on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{secrets.MT_GITHUB_TOKEN}}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        always-auth: true

    - name: Publish packages 📦
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        yarn install --frozen-lockfile
        yarn transpile
        yarn lerna publish --conventional-commits --yes --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
