/* eslint-disable */
import React from 'react'
import ReferencePage from '../../reference-page'


const ToolboxContentPage = () => (
  <ReferencePage data={{"tags":{},"filePath":"lib/components/toolbox/toolbox-content.tsx","description":"","displayName":"ToolboxContent","methods":[],"props":{"align":{"defaultValue":null,"description":"Shorthand for `alignItems` style prop","name":"align","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"alignItems\"]"}},"justify":{"defaultValue":null,"description":"Shorthand for `justifyContent` style prop","name":"justify","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"justifyContent\"]"}},"wrap":{"defaultValue":null,"description":"Shorthand for `flexWrap` style prop","name":"wrap","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"flexWrap\"]"}},"direction":{"defaultValue":{"value":"\"row\""},"description":"Shorthand for `flexDirection` style prop","name":"direction","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"flexDirection\"]"}},"basis":{"defaultValue":null,"description":"Shorthand for `flexBasis` style prop","name":"basis","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"flexBasis\"]"}},"grow":{"defaultValue":null,"description":"Shorthand for `flexGrow` style prop","name":"grow","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"flexGrow\"]"}},"shrink":{"defaultValue":null,"description":"Shorthand for `flexShrink` style prop","name":"shrink","parent":{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"},"declarations":[{"fileName":"northlight/node_modules/@chakra-ui/layout/dist/flex.d.ts","name":"FlexOptions"}],"required":false,"type":{"name":"SystemProps[\"flexShrink\"]"}}}}} />
);

export default ToolboxContentPage
